--- #YAML:1.0
name: CPAN-YACSmoke
version: 0.01
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Yet Another CPAN Smoke Tester
license: perl
requires:
  CPANPLUS: 0.051
  CPANPLUS::Backend: 0
  CPANPLUS::Configure: 0
  CPANPLUS::Error: 0
  File::HomeDir: 0.06
  File::Spec: 0.88
  File::Spec::Functions: 0
  IO::All: 0.31
  LWP::Simple: 0
  POSIX: 0
  SDBM_File: 0
  Test::Reporter: 1.25
  URI: 0
  perl: 5.6.1
build_requires:
  Test: 0
provides:
  CPAN::YACSmoke:
    file: lib/CPAN/YACSmoke.pm
    version: 0.01
generated_by: Module::Build version 0.2607
