--- #YAML:1.0
name: CPAN-YACSmoke
version: 0.03_07
author:
  - |-
    Robert Rothenberg <rrwo at cpan.org>, Barbie <barbie at cpan.org>
abstract: Yet Another CPAN Smoke Tester
license: perl
requires:
  CPANPLUS: 0.051
  Carp: 0
  Config::IniFiles: 0
  File::HomeDir: 0.06
  File::Spec: 0
  IO::File: 0
  LWP::Simple: 0
  Module::Pluggable: 2.5
  POSIX: 0
  Path::Class: 0
  Regexp::Assemble: 0.06
  SDBM_File: 0
  Sort::Versions: 1.5
  Test::Reporter: 1.25
  URI: 0
  YAML: 0
  if: 0.0401
  perl: 5.6.1
recommends:
  CPANPLUS: 0.055
  File::HomeDir::Win32: 0.02
  Pod::Readme: 0.04
  Test::Pod: 1
  Test::Pod::Coverage: 0
  Test::Portability::Files: 0
  Test::Prereq: 0
  Test::Reporter: 1.27
  YAML: 0.35
build_requires:
  File::Temp: 0
  Test::More: 0
provides:
  CPAN::YACSmoke:
    file: lib/CPAN/YACSmoke.pm
    version: 0.03_07
  CPAN::YACSmoke::Plugin::PlainTextList:
    file: lib/CPAN/YACSmoke/Plugin/PlainTextList.pm
    version: 0.01
  CPAN::YACSmoke::Plugin::Recent:
    file: lib/CPAN/YACSmoke/Plugin/Recent.pm
    version: 0.03
  CPAN::YACSmoke::Plugin::SmokeDB:
    file: lib/CPAN/YACSmoke/Plugin/SmokeDB.pm
    version: 0.01
generated_by: Module::Build version 0.261
